package com.example.ezquizbackend.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * Entity representing a quiz. Mapped to a database table by JPA
 */
@Entity
public class Quiz {
    /**
     * Primary key of the quiz entity.
     * Automatically generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy  = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title of the quiz
     */
    private String title;

    /**
     * description of the quiz
     */
    private String description;

    /**
     * No-args constructor required by JPA for creating instances
     */
    public Quiz() {
    }

    /**
     * constructs a new quiz with specified details
     *
     * @param id the primary key of the quiz, null if it is generated by the database
     * @param title the title of the quiz
     * @param description the description of the quiz
     */
    public Quiz(Long id, String title, String description) {
        this.id = id;
        this.title = title;
        this.description = description;
    }

    /**
     * gets the ID of the quiz.
     *
     * @return the ID of the quiz.
     */
    public Long getId() {
        return id;
    }

    /**
     * sets the ID of the quiz.
     *
     * @param id the ID to set.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * gets the title of the quiz.
     *
     * @return the tile of the quiz.
     */
    public String getTitle() {
        return title;
    }

    /**
     * sets the title of the quiz.
     *
     * @param title the tile set.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * gets the description of the quiz.
     *
     * @return the description of the quiz.
     */
    public String getDescription() {
        return description;
    }

    /**
     * sets the description of the quiz
     *
     * @param description the description of the quiz
     */
    public void setDescription(String description) {
        this.description = description;
    }
}
